/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./**/*.html",
    "./js/**/*.js",
    "./src/**/*.{js,jsx}",
    "./components/**/*.js",
  ],
  safelist: [
    // Regex patterns (kept minimal, no duplicates)
    {
      pattern: /^w-/,
      variants: [
        "sm",
        "md",
        "lg",
        "xl",
        "2xl",
        "top-",
        "right-",
        "left-",
        "bottom-",
        "mr-",
        "p-",
        "ms-",
        "ps-",
        "duration-",
      ],
    },
    { pattern: /^w-(0|1|2|3|4|5|6|8|10|11|12|14|16|20|24|28|32|36|40|44|45|46|48|52|56|60|64|72|80|96|auto|px|full|screen|min|max|fit)$/ },
    { pattern: /^w-(\d+(\.5)?|0|auto|px|full|screen|min|max|fit)$/ },
    { pattern: /^h-(\d+(\.5)?|0|auto|px|full|screen|min|max|fit)$/ },
    { pattern: /^p[trblxy]?-(\d+(\.5)?|0|px|full|min|max|fit)$/ },
    { pattern: /^m[trblxy]?-(\d+(\.5)?|0|auto|px|full|min|max|fit)$/ },
    { pattern: /^gap-(\d+(\.5)?|0|px|full|min|max|fit)$/ },
    { pattern: /^text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl)$/ },
    { pattern: /^ps-(\d+(\.5)?|0|px|full|min|max|fit)$/ },
    { pattern: /^pe-(\d+(\.5)?|0|px|full|min|max|fit)$/ },

    // Explicit classes (deduped)
    "-translate-x-[calc(100dvh-40px)]",
    "-translate-x-full",
    "-translate-y-1/2",
    "absolute",
    "animate-[pulse_2s_ease-in-out_infinite]",
    "animate-pulse",
    "animate-spin",
    "backdrop-blur-2xl",
    "backdrop-blur-3xl",
    "backdrop-blur-lg",
    "backdrop-blur-md",
    "backdrop-blur-none",
    "backdrop-blur-sm",
    "backdrop-blur-xl",
    "bg-black",
    "bg-black/30",
    "bg-custom-blue",
    "bg-custom-blue-light",
    "bg-custom-green",
    "bg-custom-green-light",
    "bg-custom-red",
    "bg-custom-red-dark",
    "bg-custom-red-light",
    "bg-custom-yellow",
    "bg-custom-yellow-light",
    "bg-gray-100",
    "bg-gray-900",
    "bg-green-500",
    "bg-opacity-30",
    "bg-red-500",
    "bg-teal-600",
    "bg-white",
    "bg-white/80",
    "border",
    "border-default",
    "border-gray-200",
    "border-s",
    "border-teal-600",
    "bottom-0",
    "bottom-12",
    "bottom-16",
    "bottom-20",
    "cursor-help",
    "drop-shadow-[0_0_4px_rgba(34,197,94,0.8)]",
    "drop-shadow-[0_0_4px_rgba(234,179,8,0.8)]",
    "drop-shadow-[0_0_4px_rgba(239,68,68,0.8)]",
    "drop-shadow-[0_0_4px_rgba(59,130,246,0.8)]",
    "drop-shadow-[0_0_6px_rgba(34,197,94,0.8)]",
    "drop-shadow-[0_0_6px_rgba(234,179,8,0.8)]",
    "drop-shadow-[0_0_6px_rgba(239,68,68,0.8)]",
    "drop-shadow-[0_0_6px_rgba(59,130,246,0.8)]",
    "duration-300",
    "ease-in-out",
    "ease-out",
    "fixed",
    "flex",
    "flex-col",
    "flex-shrink-0",
    "flex-end",
    "focus:outline-none",
    "font-medium",
    "gap-2",
    "gap-4",
    "gap-6",
    "gap-8",
    "grid",
    "grid-cols-1",
    "grid-cols-2",
    "grid-cols-4",
    "group",
    "group-hover:opacity-100",
    "group-hover:visible",
    "h-10",
    "h-4",
    "h-5",
    "h-6",
    "h-8",
    "h-[calc(100dvh-4rem)]",
    "h-[calc(100vh-1rem)]",
    "h-[calc(100vh-3rem)]",
    "h-[calc(100vh-40px)]",
    "h-[calc(100vh-4rem)]",
    "hidden",
    "hover:bg-custom-green-dark",
    "hover:bg-gray-100",
    "hover:bg-gray-200",
    "hover:bg-gray-50",
    "hover:bg-gray-100",
    "hover:text-teal-600",
    "inline-block",
    "inline-flex",
    "inset-0",
    "inset-x-0",
    "inset-y-0",
    "invisible",
    "items-center",
    "justify-center",
    "justify-end",
    "left-0",
    "left-1/2",
    "left-3",
    "lg:flex",
    "lg:hidden",
    "max-w-[100ch]",
    "max-w-[32ch]",
    "max-w-[40ch]",
    "max-w-[50ch]",
    "max-w-[60ch]",
    "max-w-[70ch]",
    "max-w-[80ch]",
    "max-w-[90ch]",
    "md:grid-cols-2",
    "md:pl-0",
    "min-w-80",
    "min-w-[38px]",
    "ml-2",
    "ml-4",
    "motion-safe:animate-bounce",
    "mr-1",
    "mr-4",
    "mt-10",
    "mt-3",
    "mt-6",
    "mt-8",
    "mt-auto",
    "mx-auto",
    "opacity-0",
    "opacity-70",
    "opacity-100",
    "overflow-hidden",
    "p-1.5",
    "p-4",
    "pb-2",
    "pb-3",
    "pb-4",
    "pl-10",
    "pl-16",
    "pl-4",
    "pl-6",
    "pl-8",
    "pointer-events-auto",
    "pointer-events-none",
    "pr-4",
    "px-3",
    "px-4",
    "px-6",
    "py-1",
    "py-2",
    "py-3",
    "py-4",
    "relative",
    "right-0",
    "right-2",
    "rotate-0",
    "rotate-180",
    "rounded-br-xl",
    "rounded-tr-xl",
    "rounded-xl",
    "scale-95",
    "scale-100",
    "self-end",
    "shadow-lg",
    "sm:grid-cols-2",
    "space-y-1",
    "space-y-3",
    "space-y-4",
    "space-y-6",
    "space-y-8",
    "text-2xl",
    "text-base",
    "text-blue-500",
    "text-blue-600",
    "text-custom-blue",
    "text-custom-blue-light",
    "text-custom-green",
    "text-custom-red",
    "text-custom-red-dark",
    "text-custom-red-light",
    "text-custom-yellow",
    "text-custom-yellow-light",
    "text-gray-700",
    "text-green-500",
    "text-heading",
    "text-lg",
    "text-red-500",
    "text-sm",
    "text-white",
    "text-xl",
    "text-yellow-500",
    "top-2",
    "top-4",
    "top-6",
    "top-8",
    "top-12",
    "top-16",
    "top-20",
    "top-1/2",
    "top-full",
    "transform",
    "transition",
    "transition-all",
    "transition-opacity",
    "transition-transform",
    "translate-x-full",
    "translate-y-0",
    "translate-y-4",
    "translate-y-[-10px]",
    "translate-y-[-20px]",
    "translate-y-[-30px]",
    "translate-y-[-40px]",
    "translate-y-[-50px]",
    "translate-y-[-60px]",
    "translate-y-[-70px]",
    "translate-y-[-80px]",
    "translate-y-[-90px]",
    "translate-y-[-100px]",
    "truncate",
    "w-1/2",
    "w-2/3",
    "w-4",
    "w-5",
    "w-6",
    "w-8",
    "w-full",
    "whitespace-nowrap",
    "z-40",
    "z-50",
  ],
  theme: {
    extend: {
      colors: {
        "custom-green-light": "#56B2AD", /* soft pastel green */
        "custom-green": "#157372",
        "custom-red": "#DA494E",
        "custom-red-light": "#F8C9CB",
        "custom-red-dark": "#B2222B",
        "custom-blue": "#35AADF",
        "custom-blue-light": "#A3C9FF", /* soft pastel blue */
        "custom-blue1": "#3366CC", /* darker base blue */
        "custom-yellow-light": "#FFF2B8", /* soft pastel yellow */
        "custom-yellow": "#FFE066", /* slightly stronger on hover */
        "custom-orange-light": "#FFDAB3", /* soft pastel orange */
        "custom-orange": "#FFA64D", /* slightly stronger on hover */
        heading: "#111827",
        body: "#6B7280",
      },
      width: {
        "45": "11.25rem", // 180px
        "46": "11.5rem", // 184px
        "47": "11.75rem", // 188px
      },
    },
  },
  plugins: [],
};